### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by noelfoka** [mershark/My-Portfolio#10]
We notice that you have done a great job, but some details are missing. please follow the following instructions:

- [ ] Your about me section social media icons are not properly aligned, we suggest you use "align center" to align all the social media icons.
  Figma design:
![image](https://github.com/mershark/My-Portfolio/assets/116439136/47288e3e-07ba-46ee-a064-8a5cb151fa8c)
  your design: 
![image](https://github.com/mershark/My-Portfolio/assets/116439136/6a21a579-80a2-4241-9760-770f78cf7320)

- [ ] We would like you to add "cursor: pointer" to Portfolio, About and Contact.
- [ ] your design
![image](https://github.com/mershark/My-Portfolio/assets/116439136/803d6352-d556-4b26-bc78-e9d6543b9cce)
   figma design:
![image](https://github.com/mershark/My-Portfolio/assets/116439136/1e094cd7-0b1b-4280-bb39-e5ee72603376)
add these icons please

- [ ]

**Comment by mershark** [comment]
Thank you
