### ISSUE TITLE
:art: Enhancement of the UI

### ISSUE THREAD

**Issue by nejidevelops** [mershark/My-Portfolio#4]
# Some enhancements needs to be worked out, I hope you can work on them and make your portfolio professional :sunglasses: 

## The enhancements

- The project needs to be created based on the Figma template provided.
    - [x] Make good implementation of HTML and CSS to get your contact form perfectly matching with the Figma one
    - [x] Make good use of CSS flex and grid to lay and position your elements accordingly.
    - [x] Apply some width and heights to your inputs and textarea to match the defined Figma values

## Implementation

- [x] Get the languages, skills and framework sections well laid but use ul and lis when listing them.
- [x] Get the two divs flexed left and right by using css flexbox.
- [x] Make sure the form and it's content are centered by using either justify-content and align-items properties. 

![Screenshot from 2023-06-09 10-27-11](https://github.com/mershark/My-Portfolio/assets/79839603/4a8ff989-0a72-4766-b2f9-6289d8d61473)
![Screenshot from 2023-06-09 10-26-56](https://github.com/mershark/My-Portfolio/assets/79839603/ed91122a-121a-4f0b-92f7-eb536572a010)

  **Looking at the screenshots above, you need to implement your code to be a match of this.**

# Acceptance criteria
- [x] CSS flex and grid are used to lay the html elements
- [x] CSS form works well and is integrated with [Formspree services](https://formspree.io/forms/xvonjbwr/integration)
- [x] Semantic html are used to wrap

**Comment by mershark** [comment]
All issues have been solved
